chain:
    bech32_prefix: cft
    modules: 
        - modules
        - messages
        - auth
        - actions
        - bank
        - consensus
        - feegrant
        - gov
        - inflation
        - pricefeed
        - slashing
        - staking
        - distribution
        - upgrade
node:
    type: remote
    config:
        rpc:
            client_name: confid
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
# node:
#     type: local
#     config:
#         home: /root/.confid
parsing:
    workers: 1
    start_height: 1
    average_block_time: 3s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    fast_sync: true
    genesis_file_path: /var/www/html/genesis.json
    
database:
    url: postgresql://goldman:123QWEqwe%21%23@localhost:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: cft
          units:
            - denom: cft
              exponent: 18
             
actions:
    host: 0.0.0.0
    port: 3000
    node:
        rpc:
            client_name: hasura-actions
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
